# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'gitStudent' do

  pod 'fishhook'

end
